<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Synonym;

class SynonymSeeder extends Seeder {
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() 
    {
        $synonyms = [
            // --- EVENTOS Y ACTIVIDADES ---
            ['palabra' => 'evento', 'sinonimo' => 'actividad'],
            ['palabra' => 'evento', 'sinonimo' => 'acto'],
            ['palabra' => 'evento', 'sinonimo' => 'encuentro'],
            ['palabra' => 'evento', 'sinonimo' => 'reunion'],
            ['palabra' => 'actividad', 'sinonimo' => 'evento'],
            ['palabra' => 'seminario', 'sinonimo' => 'conferencia'],
            ['palabra' => 'seminario', 'sinonimo' => 'charla'],
            ['palabra' => 'conferencia', 'sinonimo' => 'charla'],
            ['palabra' => 'conferencia', 'sinonimo' => 'ponencia'],
            ['palabra' => 'taller', 'sinonimo' => 'workshop'],
            ['palabra' => 'taller', 'sinonimo' => 'curso'],
            ['palabra' => 'curso', 'sinonimo' => 'taller'],
            // Nuevos sinónimos para Eventos y Actividades
            ['palabra' => 'celebracion', 'sinonimo' => 'festejo'],
            ['palabra' => 'jornada', 'sinonimo' => 'dia'],
            ['palabra' => 'jornada', 'sinonimo' => 'sesion'],
            ['palabra' => 'programa', 'sinonimo' => 'horario'],
            ['palabra' => 'programa', 'sinonimo' => 'plan'],
            ['palabra' => 'cita', 'sinonimo' => 'encuentro'],
            ['palabra' => 'cita', 'sinonimo' => 'entrevista'],
            ['palabra' => 'reunion', 'sinonimo' => 'junta'],
            ['palabra' => 'sesion', 'sinonimo' => 'reunion'],
            ['palabra' => 'presentacion', 'sinonimo' => 'exposicion'],
            ['palabra' => 'clase', 'sinonimo' => 'leccion'],
            ['palabra' => 'demostracion', 'sinonimo' => 'muestra'],
            ['palabra' => 'webinar', 'sinonimo' => 'seminario web'],
            ['palabra' => 'webinar', 'sinonimo' => 'conferencia en linea'],

            // --- INGENIERÍA Y TECNOLOGÍA ---
            ['palabra' => 'ingenieria', 'sinonimo' => 'ingenieril'],
            ['palabra' => 'ingenieria', 'sinonimo' => 'tecnica'],
            ['palabra' => 'tecnologia', 'sinonimo' => 'tecnica'],
            ['palabra' => 'tecnologia', 'sinonimo' => 'innovacion'],
            ['palabra' => 'software', 'sinonimo' => 'programa'],
            ['palabra' => 'software', 'sinonimo' => 'aplicacion'],
            ['palabra' => 'hardware', 'sinonimo' => 'equipo'],
            ['palabra' => 'hardware', 'sinonimo' => 'computadora'],
            ['palabra' => 'computadora', 'sinonimo' => 'ordenador'],
            ['palabra' => 'computadora', 'sinonimo' => 'pc'],
            // Nuevos sinónimos para Ingeniería y Tecnología
            ['palabra' => 'aplicacion', 'sinonimo' => 'app'],
            ['palabra' => 'aplicacion', 'sinonimo' => 'software'],
            ['palabra' => 'sistema', 'sinonimo' => 'plataforma'],
            ['palabra' => 'dispositivo', 'sinonimo' => 'aparato'],
            ['palabra' => 'dispositivo', 'sinonimo' => 'terminal'],
            ['palabra' => 'desarrollo', 'sinonimo' => 'programacion'],
            ['palabra' => 'desarrollo', 'sinonimo' => 'creacion'],
            ['palabra' => 'redes', 'sinonimo' => 'conectividad'],
            ['palabra' => 'servidor', 'sinonimo' => 'host'],
            ['palabra' => 'base de datos', 'sinonimo' => 'bd'],
            ['palabra' => 'algoritmo', 'sinonimo' => 'logica'],
            ['palabra' => 'codigo', 'sinonimo' => 'script'],
            ['palabra' => 'programacion', 'sinonimo' => 'codificacion'],
            ['palabra' => 'internet', 'sinonimo' => 'web'],

            // --- PROBLEMAS Y SOLUCIONES ---
            ['palabra' => 'problema', 'sinonimo' => 'dificultad'],
            ['palabra' => 'problema', 'sinonimo' => 'inconveniente'],
            ['palabra' => 'problema', 'sinonimo' => 'contratiempo'],
            ['palabra' => 'error', 'sinonimo' => 'falla'],
            ['palabra' => 'error', 'sinonimo' => 'fallo'],
            ['palabra' => 'error', 'sinonimo' => 'equivocacion'],
            ['palabra' => 'falla', 'sinonimo' => 'defecto'],
            ['palabra' => 'falla', 'sinonimo' => 'averia'],
            ['palabra' => 'solucion', 'sinonimo' => 'respuesta'],
            ['palabra' => 'solucion', 'sinonimo' => 'solucionar'],
            ['palabra' => 'arreglar', 'sinonimo' => 'reparar'],
            ['palabra' => 'arreglar', 'sinonimo' => 'corregir'],
            // Nuevos sinónimos para Problemas y Soluciones
            ['palabra' => 'duda', 'sinonimo' => 'pregunta'],
            ['palabra' => 'duda', 'sinonimo' => 'consulta'],
            ['palabra' => 'arreglo', 'sinonimo' => 'reparacion'],
            ['palabra' => 'solucionar', 'sinonimo' => 'resolver'],
            ['palabra' => 'incidente', 'sinonimo' => 'problema'],
            ['palabra' => 'incidencia', 'sinonimo' => 'problema'],
            ['palabra' => 'fallo', 'sinonimo' => 'bug'],
            ['palabra' => 'diagnostico', 'sinonimo' => 'analisis'],
            ['palabra' => 'mantenimiento', 'sinonimo' => 'soporte tecnico'],
            ['palabra' => 'soporte', 'sinonimo' => 'ayuda'],
            ['palabra' => 'reclamacion', 'sinonimo' => 'queja'],
            ['palabra' => 'averia', 'sinonimo' => 'danio'],

            // --- TIEMPO Y FECHAS ---
            ['palabra' => 'fecha', 'sinonimo' => 'dia'],
            ['palabra' => 'fecha', 'sinonimo' => 'fechas'],
            ['palabra' => 'hora', 'sinonimo' => 'horario'],
            ['palabra' => 'hora', 'sinonimo' => 'tiempo'],
            ['palabra' => 'mañana', 'sinonimo' => 'amanecer'],
            ['palabra' => 'tarde', 'sinonimo' => 'atardecer'],
            ['palabra' => 'noche', 'sinonimo' => 'nocturno'],
            ['palabra' => 'urgente', 'sinonimo' => 'inmediato'],
            ['palabra' => 'urgente', 'sinonimo' => 'prioritario'],
            ['palabra' => 'pronto', 'sinonimo' => 'rapido'],
            // Nuevos sinónimos para Tiempo y Fechas
            ['palabra' => 'calendario', 'sinonimo' => 'agenda'],
            ['palabra' => 'plazo', 'sinonimo' => 'fecha limite'],
            ['palabra' => 'actual', 'sinonimo' => 'presente'],
            ['palabra' => 'anterior', 'sinonimo' => 'pasado'],
            ['palabra' => 'proximo', 'sinonimo' => 'siguiente'],
            ['palabra' => 'vencimiento', 'sinonimo' => 'caducidad'],
            ['palabra' => 'periodo', 'sinonimo' => 'lapso'],
            ['palabra' => 'semanal', 'sinonimo' => 'cada semana'],
            ['palabra' => 'mensual', 'sinonimo' => 'cada mes'],
            ['palabra' => 'anual', 'sinonimo' => 'cada anio'],
            ['palabra' => 'rapido', 'sinonimo' => 'veloz'],
            ['palabra' => 'inmediato', 'sinonimo' => 'ahora'],

            // --- LUGARES Y UBICACIONES ---
            ['palabra' => 'lugar', 'sinonimo' => 'ubicacion'],
            ['palabra' => 'lugar', 'sinonimo' => 'sitio'],
            ['palabra' => 'lugar', 'sinonimo' => 'localizacion'],
            ['palabra' => 'auditorio', 'sinonimo' => 'salon'],
            ['palabra' => 'auditorio', 'sinonimo' => 'sala'],
            ['palabra' => 'oficina', 'sinonimo' => 'despacho'],
            ['palabra' => 'edificio', 'sinonimo' => 'construccion'],
            ['palabra' => 'edificio', 'sinonimo' => 'inmueble'],
            // Nuevos sinónimos para Lugares y Ubicaciones
            ['palabra' => 'campus', 'sinonimo' => 'recinto'],
            ['palabra' => 'direccion', 'sinonimo' => 'ubicacion'],
            ['palabra' => 'area', 'sinonimo' => 'zona'],
            ['palabra' => 'piso', 'sinonimo' => 'planta'],
            ['palabra' => 'entrada', 'sinonimo' => 'acceso'],
            ['palabra' => 'sede', 'sinonimo' => 'central'],
            ['palabra' => 'matriz', 'sinonimo' => 'sede principal'],
            ['palabra' => 'filial', 'sinonimo' => 'sucursal'],
            ['palabra' => 'sala', 'sinonimo' => 'habitacion'],
            ['palabra' => 'aula', 'sinonimo' => 'salon de clases'],
            ['palabra' => 'laboratorio', 'sinonimo' => 'lab'],
            ['palabra' => 'externo', 'sinonimo' => 'fuera'],
            ['palabra' => 'interno', 'sinonimo' => 'dentro'],

            // --- PERSONAS Y CONTACTOS ---
            ['palabra' => 'persona', 'sinonimo' => 'individuo'],
            ['palabra' => 'persona', 'sinonimo' => 'usuario'],
            ['palabra' => 'usuario', 'sinonimo' => 'cliente'],
            ['palabra' => 'cliente', 'sinonimo' => 'consumidor'],
            ['palabra' => 'profesor', 'sinonimo' => 'docente'],
            ['palabra' => 'profesor', 'sinonimo' => 'maestro'],
            ['palabra' => 'estudiante', 'sinonimo' => 'alumno'],
            ['palabra' => 'estudiante', 'sinonimo' => 'educando'],
            ['palabra' => 'ayuda', 'sinonimo' => 'asistencia'],
            ['palabra' => 'ayuda', 'sinonimo' => 'soporte'],
            // Nuevos sinónimos para Personas y Contactos
            ['palabra' => 'contacto', 'sinonimo' => 'informacion de contacto'],
            ['palabra' => 'contacto', 'sinonimo' => 'telefono'],
            ['palabra' => 'personal', 'sinonimo' => 'empleado'],
            ['palabra' => 'personal', 'sinonimo' => 'trabajador'],
            ['palabra' => 'jefe', 'sinonimo' => 'supervisor'],
            ['palabra' => 'jefe', 'sinonimo' => 'encargado'],
            ['palabra' => 'colega', 'sinonimo' => 'companiero'],
            ['palabra' => 'empleado', 'sinonimo' => 'colaborador'],
            ['palabra' => 'asesor', 'sinonimo' => 'consultor'],
            ['palabra' => 'director', 'sinonimo' => 'gerente'],
            ['palabra' => 'equipo', 'sinonimo' => 'staff'],
            ['palabra' => 'alumnos', 'sinonimo' => 'estudiantes'],
            ['palabra' => 'usuario', 'sinonimo' => 'user'],

            // --- ACADÉMICO Y EDUCACIÓN ---
            ['palabra' => 'universidad', 'sinonimo' => 'universitario'],
            ['palabra' => 'universidad', 'sinonimo' => 'facultad'],
            ['palabra' => 'carrera', 'sinonimo' => 'estudio'],
            ['palabra' => 'carrera', 'sinonimo' => 'licenciatura'],
            ['palabra' => 'examen', 'sinonimo' => 'evaluacion'],
            ['palabra' => 'examen', 'sinonimo' => 'prueba'],
            ['palabra' => 'examen', 'sinonimo' => 'test'],
            ['palabra' => 'calificacion', 'sinonimo' => 'nota'],
            ['palabra' => 'calificacion', 'sinonimo' => 'puntuacion'],
            ['palabra' => 'aprender', 'sinonimo' => 'estudiar'],
            ['palabra' => 'aprender', 'sinonimo' => 'instruirse'],
            // Nuevos sinónimos para Académico y Educación
            ['palabra' => 'grado', 'sinonimo' => 'titulo'],
            ['palabra' => 'materia', 'sinonimo' => 'asignatura'],
            ['palabra' => 'inscripcion', 'sinonimo' => 'registro'],
            ['palabra' => 'investigacion', 'sinonimo' => 'estudio'],
            ['palabra' => 'investigacion', 'sinonimo' => 'analisis'],
            ['palabra' => 'tesis', 'sinonimo' => 'proyecto final'],
            ['palabra' => 'departamento', 'sinonimo' => 'area'],
            ['palabra' => 'semestre', 'sinonimo' => 'periodo'],
            ['palabra' => 'programa academico', 'sinonimo' => 'curricula'],
            ['palabra' => 'maestria', 'sinonimo' => 'postgrado'],
            ['palabra' => 'doctorado', 'sinonimo' => 'phd'],

            // --- DOCUMENTOS Y ARCHIVOS ---
            ['palabra' => 'documento', 'sinonimo' => 'archivo'],
            ['palabra' => 'documento', 'sinonimo' => 'papel'],
            ['palabra' => 'informe', 'sinonimo' => 'reporte'],
            ['palabra' => 'informe', 'sinonimo' => 'reportaje'],
            ['palabra' => 'formulario', 'sinonimo' => 'formato'],
            ['palabra' => 'formulario', 'sinonimo' => 'formularios'],
            ['palabra' => 'solicitud', 'sinonimo' => 'peticion'],
            ['palabra' => 'solicitud', 'sinonimo' => 'requerimiento'],
            // Nuevos sinónimos para Documentos y Archivos
            ['palabra' => 'manual', 'sinonimo' => 'guia'],
            ['palabra' => 'credencial', 'sinonimo' => 'identificacion'],
            ['palabra' => 'expediente', 'sinonimo' => 'registro'],
            ['palabra' => 'copia', 'sinonimo' => 'ejemplar'],
            ['palabra' => 'descarga', 'sinonimo' => 'bajar'],
            ['palabra' => 'poliza', 'sinonimo' => 'seguro'],
            ['palabra' => 'contrato', 'sinonimo' => 'acuerdo'],
            ['palabra' => 'factura', 'sinonimo' => 'recibo'],
            ['palabra' => 'recibo', 'sinonimo' => 'comprobante'],
            ['palabra' => 'archivar', 'sinonimo' => 'guardar'],
            ['palabra' => 'pdf', 'sinonimo' => 'documento'],
            ['palabra' => 'adjunto', 'sinonimo' => 'anexo'],

            // --- SISTEMAS Y REDES ---
            ['palabra' => 'sistema', 'sinonimo' => 'plataforma'],
            ['palabra' => 'sistema', 'sinonimo' => 'sistemas'],
            ['palabra' => 'red', 'sinonimo' => 'network'],
            ['palabra' => 'internet', 'sinonimo' => 'web'],
            ['palabra' => 'internet', 'sinonimo' => 'online'],
            ['palabra' => 'pagina', 'sinonimo' => 'web'],
            ['palabra' => 'pagina', 'sinonimo' => 'sitio'],
            ['palabra' => 'contraseña', 'sinonimo' => 'password'],
            ['palabra' => 'contraseña', 'sinonimo' => 'clave'],
            ['palabra' => 'usuario', 'sinonimo' => 'username'],
            // Nuevos sinónimos para Sistemas y Redes
            ['palabra' => 'servidor', 'sinonimo' => 'server'],
            ['palabra' => 'acceso', 'sinonimo' => 'login'],
            ['palabra' => 'cuenta', 'sinonimo' => 'perfil'],
            ['palabra' => 'navegador', 'sinonimo' => 'browser'],
            ['palabra' => 'enlace', 'sinonimo' => 'link'],
            ['palabra' => 'conexion', 'sinonimo' => 'enlace'],
            ['palabra' => 'router', 'sinonimo' => 'modem'],
            ['palabra' => 'seguridad', 'sinonimo' => 'proteccion'],
            ['palabra' => 'firewall', 'sinonimo' => 'cortafuegos'],
            ['palabra' => 'nube', 'sinonimo' => 'cloud'],
            ['palabra' => 'datos', 'sinonimo' => 'informacion'],
            ['palabra' => 'actualizar', 'sinonimo' => 'refrescar'],

            // --- ESTADOS Y CONDICIONES ---
            ['palabra' => 'activo', 'sinonimo' => 'activado'],
            ['palabra' => 'activo', 'sinonimo' => 'funcionando'],
            ['palabra' => 'inactivo', 'sinonimo' => 'desactivado'],
            ['palabra' => 'inactivo', 'sinonimo' => 'parado'],
            ['palabra' => 'completo', 'sinonimo' => 'terminado'],
            ['palabra' => 'completo', 'sinonimo' => 'finalizado'],
            ['palabra' => 'pendiente', 'sinonimo' => 'espera'],
            ['palabra' => 'pendiente', 'sinonimo' => 'proceso'],
            // Nuevos sinónimos para Estados y Condiciones
            ['palabra' => 'listo', 'sinonimo' => 'preparado'],
            ['palabra' => 'disponible', 'sinonimo' => 'accesible'],
            ['palabra' => 'agotado', 'sinonimo' => 'vendido'],
            ['palabra' => 'agotado', 'sinonimo' => 'terminado'],
            ['palabra' => 'habilitado', 'sinonimo' => 'activado'],
            ['palabra' => 'deshabilitado', 'sinonimo' => 'inactivo'],
            ['palabra' => 'procesando', 'sinonimo' => 'en curso'],
            ['palabra' => 'completado', 'sinonimo' => 'listo'],
            ['palabra' => 'fallido', 'sinonimo' => 'erroneo'],
            ['palabra' => 'obsoleto', 'sinonimo' => 'antiguo'],
            ['palabra' => 'nuevo', 'sinonimo' => 'fresco'],
            ['palabra' => 'en linea', 'sinonimo' => 'conectado'],

            // --- VERBOS COMUNES ---
            ['palabra' => 'buscar', 'sinonimo' => 'encontrar'],
            ['palabra' => 'buscar', 'sinonimo' => 'localizar'],
            ['palabra' => 'buscar', 'sinonimo' => 'hallar'],
            ['palabra' => 'necesitar', 'sinonimo' => 'requerir'],
            ['palabra' => 'necesitar', 'sinonimo' => 'precisar'],
            ['palabra' => 'querer', 'sinonimo' => 'desear'],
            ['palabra' => 'poder', 'sinonimo' => 'capacidad'],
            ['palabra' => 'poder', 'sinonimo' => 'facultad'],
            ['palabra' => 'saber', 'sinonimo' => 'conocer'],
            ['palabra' => 'saber', 'sinonimo' => 'informarse'],
            // Nuevos sinónimos para Verbos Comunes
            ['palabra' => 'cambiar', 'sinonimo' => 'modificar'],
            ['palabra' => 'cambiar', 'sinonimo' => 'reemplazar'],
            ['palabra' => 'crear', 'sinonimo' => 'generar'],
            ['palabra' => 'crear', 'sinonimo' => 'hacer'],
            ['palabra' => 'enviar', 'sinonimo' => 'mandar'],
            ['palabra' => 'recibir', 'sinonimo' => 'obtener'],
            ['palabra' => 'gestionar', 'sinonimo' => 'administrar'],
            ['palabra' => 'administrar', 'sinonimo' => 'manejar'],
            ['palabra' => 'confirmar', 'sinonimo' => 'validar'],
            ['palabra' => 'cancelar', 'sinonimo' => 'anular'],
            ['palabra' => 'iniciar', 'sinonimo' => 'empezar'],
            ['palabra' => 'finalizar', 'sinonimo' => 'terminar'],
            ['palabra' => 'subir', 'sinonimo' => 'upload'],
            ['palabra' => 'bajar', 'sinonimo' => 'download'],
            ['palabra' => 'ingresar', 'sinonimo' => 'entrar'],
            ['palabra' => 'salir', 'sinonimo' => 'logout'],

            // --- ADJETIVOS COMUNES ---
            ['palabra' => 'bueno', 'sinonimo' => 'excelente'],
            ['palabra' => 'bueno', 'sinonimo' => 'optimoo'],
            ['palabra' => 'bueno', 'sinonimo' => 'positivo'],
            ['palabra' => 'malo', 'sinonimo' => 'negativo'],
            ['palabra' => 'malo', 'sinonimo' => 'deficiente'],
            ['palabra' => 'malo', 'sinonimo' => 'pobre'],
            ['palabra' => 'rapido', 'sinonimo' => 'veloz'],
            ['palabra' => 'rapido', 'sinonimo' => 'agil'],
            ['palabra' => 'lento', 'sinonimo' => 'pausado'],
            ['palabra' => 'lento', 'sinonimo' => 'despacio'],
            ['palabra' => 'facil', 'sinonimo' => 'sencillo'],
            ['palabra' => 'facil', 'sinonimo' => 'simple'],
            ['palabra' => 'dificil', 'sinonimo' => 'complicado'],
            ['palabra' => 'dificil', 'sinonimo' => 'complejo'],
            // Nuevos sinónimos para Adjetivos Comunes
            ['palabra' => 'grande', 'sinonimo' => 'mayor'],
            ['palabra' => 'pequeno', 'sinonimo' => 'menor'],
            ['palabra' => 'importante', 'sinonimo' => 'relevante'],
            ['palabra' => 'nuevo', 'sinonimo' => 'reciente'],
            ['palabra' => 'antiguo', 'sinonimo' => 'viejo'],
            ['palabra' => 'general', 'sinonimo' => 'comun'],
            ['palabra' => 'esencial', 'sinonimo' => 'vital'],
            ['palabra' => 'critico', 'sinonimo' => 'urgente'],
            ['palabra' => 'opcional', 'sinonimo' => 'secundario'],
            ['palabra' => 'primario', 'sinonimo' => 'principal'],
            ['palabra' => 'secundario', 'sinonimo' => 'acceso'],
            ['palabra' => 'digital', 'sinonimo' => 'electronico'],
            ['palabra' => 'fisico', 'sinonimo' => 'impreso'],
            ['palabra' => 'gratuito', 'sinonimo' => 'libre'],

            // --- CORRECCIONES ORTOGRÁFICAS COMUNES ---
            ['palabra' => 'probelema', 'sinonimo' => 'problema'],
            ['palabra' => 'probrema', 'sinonimo' => 'problema'],
            ['palabra' => 'ingeneria', 'sinonimo' => 'ingenieria'],
            ['palabra' => 'ingenieria', 'sinonimo' => 'ingenieria'], // Duplicado de la original, la mantengo si acaso
            ['palabra' => 'eveneto', 'sinonimo' => 'evento'],
            ['palabra' => 'evneto', 'sinonimo' => 'evento'],
            ['palabra' => 'sistemas', 'sinonimo' => 'sistema'],
            ['palabra' => 'sistma', 'sinonimo' => 'sistema'],
            ['palabra' => 'universida', 'sinonimo' => 'universidad'],
            ['palabra' => 'univercidad', 'sinonimo' => 'universidad'],
            ['palabra' => 'documeto', 'sinonimo' => 'documento'],
            ['palabra' => 'documneto', 'sinonimo' => 'documento'],
            ['palabra' => 'informacion', 'sinonimo' => 'informacion'], // Duplicado de la original, la mantengo si acaso
            ['palabra' => 'informcion', 'sinonimo' => 'informacion'],
            // Nuevas correcciones ortográficas
            ['palabra' => 'conferecnia', 'sinonimo' => 'conferencia'],
            ['palabra' => 'talleer', 'sinonimo' => 'taller'],
            ['palabra' => 'solucionn', 'sinonimo' => 'solucion'],
            ['palabra' => 'ussuario', 'sinonimo' => 'usuario'],
            ['palabra' => 'tecnolgia', 'sinonimo' => 'tecnologia'],
            ['palabra' => 'compuadora', 'sinonimo' => 'computadora'],
            ['palabra' => 'tecnolojia', 'sinonimo' => 'tecnologia'],
            ['palabra' => 'profesorr', 'sinonimo' => 'profesor'],
            ['palabra' => 'accesoo', 'sinonimo' => 'acceso'],
            ['palabra' => 'dirección', 'sinonimo' => 'direccion'], // Corrige acento
            ['palabra' => 'mantenimeinto', 'sinonimo' => 'mantenimiento'],
        ];

        foreach ($synonyms as $synonym) {
            // Asegura que no se cree si ya existe un par idéntico (aunque la revisión manual minimiza esto)
            Synonym::firstOrCreate($synonym); 
        }
    }
}